// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxOyQ7_tWLrtWMP4QxhizF3wiygoEhsg',
    appId: '1:1031885922470:web:22c6ceb71512e552539467',
    messagingSenderId: '1031885922470',
    projectId: 'trialapp-c71dd',
    authDomain: 'trialapp-c71dd.firebaseapp.com',
    storageBucket: 'trialapp-c71dd.appspot.com',
    measurementId: 'G-JTBN0QZDE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYKQ9ab0kXc_9ounsEurw0sjmQ7KlYgk',
    appId: '1:1031885922470:android:20d7f4d910adb974539467',
    messagingSenderId: '1031885922470',
    projectId: 'trialapp-c71dd',
    storageBucket: 'trialapp-c71dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBOwmLlQzajXRBK8L-KDvS1xppSdZUcc',
    appId: '1:1031885922470:ios:7f55e278efe50c5a539467',
    messagingSenderId: '1031885922470',
    projectId: 'trialapp-c71dd',
    storageBucket: 'trialapp-c71dd.appspot.com',
    iosBundleId: 'com.example.mxperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBOwmLlQzajXRBK8L-KDvS1xppSdZUcc',
    appId: '1:1031885922470:ios:d2fe4b12b28a99fb539467',
    messagingSenderId: '1031885922470',
    projectId: 'trialapp-c71dd',
    storageBucket: 'trialapp-c71dd.appspot.com',
    iosBundleId: 'com.example.mxperts.RunnerTests',
  );
}
